# Script mode. Composes version-free shader bodies into a header of OpenGL dialect
# string constants. MANIFEST is a comma separated list of constant=file entries and
# every file is read from SHADER_DIR. An include line is replaced by a newline plus
# the named chunk file, so the composed bytes stay identical to the strings that
# were previously embedded in the C++ sources. When DEPFILE is set the script also
# writes a make format dependency file naming every body and chunk it read, so a
# future include edit rebuilds the header without touching the DEPENDS list.

if(NOT DEFINED SHADER_DIR OR NOT DEFINED OUTPUT OR NOT DEFINED NAMESPACE OR NOT DEFINED MANIFEST)
    message(FATAL_ERROR "RabbetShaderCompose needs SHADER_DIR, OUTPUT, NAMESPACE and MANIFEST")
endif()

# The source include path is searched ahead of the generated one, so a stray header
# beside the shader files would silently shadow every composed constant.
if(EXISTS "${SHADER_DIR}/GlShaderSources.h")
    message(FATAL_ERROR "remove ${SHADER_DIR}/GlShaderSources.h, it would shadow the generated header")
endif()

set(directive "#include \"")
string(LENGTH "${directive}" directive_length)

string(REPLACE "," ";" entries "${MANIFEST}")

set(read_files "")
set(header "#pragma once\n\n")
string(APPEND header "// Generated by cmake/RabbetShaderCompose.cmake from the shader files.\n")
string(APPEND header "// Edit those files, never this header.\n\n")
string(APPEND header "namespace ${NAMESPACE} {\n")

foreach(entry IN LISTS entries)
    string(REGEX MATCH "^([A-Za-z0-9_]+)=(.+)$" matched "${entry}")
    if(NOT matched)
        message(FATAL_ERROR "malformed manifest entry '${entry}'")
    endif()
    set(constant "${CMAKE_MATCH_1}")
    set(body_file "${SHADER_DIR}/${CMAKE_MATCH_2}")
    if(NOT EXISTS "${body_file}")
        message(FATAL_ERROR "manifest entry '${entry}' names a missing file ${body_file}")
    endif()
    file(READ "${body_file}" remaining)
    list(APPEND read_files "${body_file}")

    set(expanded "")
    while(TRUE)
        string(FIND "${remaining}" "${directive}" position)
        if(position EQUAL -1)
            string(APPEND expanded "${remaining}")
            break()
        endif()
        if(position GREATER 0)
            math(EXPR before "${position} - 1")
            string(SUBSTRING "${remaining}" ${before} 1 previous_char)
            if(NOT previous_char STREQUAL "\n")
                message(FATAL_ERROR "${body_file} has an include that does not start a line")
            endif()
        endif()
        string(SUBSTRING "${remaining}" 0 ${position} prefix)
        string(APPEND expanded "${prefix}")
        math(EXPR name_start "${position} + ${directive_length}")
        string(SUBSTRING "${remaining}" ${name_start} -1 tail)
        string(FIND "${tail}" "\"" name_end)
        if(name_end EQUAL -1)
            message(FATAL_ERROR "${body_file} has an unterminated include name")
        endif()
        string(SUBSTRING "${tail}" 0 ${name_end} chunk_name)
        math(EXPR line_end "${name_end} + 1")
        string(SUBSTRING "${tail}" ${line_end} 1 line_terminator)
        if(NOT line_terminator STREQUAL "\n")
            message(FATAL_ERROR "${body_file} include line for '${chunk_name}' must end the line")
        endif()
        if(NOT EXISTS "${SHADER_DIR}/${chunk_name}")
            message(FATAL_ERROR "${body_file} includes missing chunk '${chunk_name}'")
        endif()
        file(READ "${SHADER_DIR}/${chunk_name}" chunk)
        list(APPEND read_files "${SHADER_DIR}/${chunk_name}")
        string(APPEND expanded "\n${chunk}")
        math(EXPR next_start "${line_end} + 1")
        string(SUBSTRING "${tail}" ${next_start} -1 remaining)
    endwhile()

    string(FIND "${expanded}" "#version" version_position)
    if(NOT version_position EQUAL -1)
        message(FATAL_ERROR "${body_file} or a chunk it includes must stay version free, the composer owns the version line")
    endif()
    # A directive surviving expansion means a chunk carried its own include, which the
    # single level scan above never resolves.
    string(FIND "${expanded}" "${directive}" leftover_position)
    if(NOT leftover_position EQUAL -1)
        message(FATAL_ERROR "${body_file} expanded to text that still contains an include directive")
    endif()

    string(APPEND header "\ninline constexpr const char* ${constant} = R\"RBGLSL(#version 410 core\n")
    string(APPEND header "${expanded})RBGLSL\";\n")
endforeach()

string(APPEND header "\n} // namespace ${NAMESPACE}\n")

file(WRITE "${OUTPUT}" "${header}")

if(DEFINED DEPFILE)
    list(REMOVE_DUPLICATES read_files)
    # Make prerequisite syntax splits on unescaped spaces, so a spaced checkout path
    # must arrive backslash escaped or it turns into bogus prerequisites.
    set(escaped_files "")
    foreach(read_file IN LISTS read_files)
        string(REPLACE " " "\\ " read_file "${read_file}")
        list(APPEND escaped_files "${read_file}")
    endforeach()
    string(REPLACE " " "\\ " escaped_output "${OUTPUT}")
    string(JOIN " " dependency_line ${escaped_files})
    file(WRITE "${DEPFILE}" "${escaped_output}: ${dependency_line}\n")
endif()
