# Script mode. Composes version-free shader bodies for one GLSL dialect. The default
# 410 invocation emits a header of OpenGL dialect string constants and MANIFEST is a
# comma separated list of constant=file entries, every file read from SHADER_DIR. An
# include line is replaced by a newline plus the named chunk file, so the composed
# bytes stay identical to the strings that were previously embedded in the C++
# sources. A DIALECT of 450 instead writes the single manifest entry as composed GLSL
# text to OUTPUT for glslc. Entries named in the optional PRELUDE list receive the
# dialect prelude after the version line; entries outside the list compose byte for
# byte as before. When DEPFILE is set the script also writes a make format dependency
# file naming every body and chunk it read, so a future include edit rebuilds the
# output without touching the DEPENDS list.

if(NOT DEFINED DIALECT)
    set(DIALECT 410)
endif()
if(NOT DIALECT STREQUAL "410" AND NOT DIALECT STREQUAL "450")
    message(FATAL_ERROR "RabbetShaderCompose DIALECT must be 410 or 450, got '${DIALECT}'")
endif()
if(NOT DEFINED SHADER_DIR OR NOT DEFINED OUTPUT OR NOT DEFINED MANIFEST)
    message(FATAL_ERROR "RabbetShaderCompose needs SHADER_DIR, OUTPUT and MANIFEST")
endif()
if(DIALECT STREQUAL "410" AND NOT DEFINED NAMESPACE)
    message(FATAL_ERROR "RabbetShaderCompose needs NAMESPACE for the 410 header")
endif()

# The source include path is searched ahead of the generated one, so a stray header
# beside the shader files would silently shadow every composed constant.
if(EXISTS "${SHADER_DIR}/GlShaderSources.h")
    message(FATAL_ERROR "remove ${SHADER_DIR}/GlShaderSources.h, it would shadow the generated header")
endif()

# The prelude maps one shader body onto both resource models. OpenGL keeps material
# and light values as loose uniforms while the camera uses its existing block. Vulkan
# assigns those values to the fixed frame and draw descriptor sets, and moves transform
# data into a bounded push block.
set(prelude_410 "#define RB_PER_FRAME_BEGIN layout(std140) uniform RbPerFrame {\n#define RB_PER_FRAME_END };\n#define RB_PER_DRAW_BEGIN\n#define RB_PER_DRAW_END\n#define RB_PER_DRAW(declaration) uniform declaration;\n#define RB_PER_DRAW_AT(declaration, byte_offset) uniform declaration;\n#define RB_LIGHT_FRAME_BEGIN\n#define RB_LIGHT_FRAME_END\n#define RB_LIGHT_FRAME_AT(declaration, byte_offset) uniform declaration;\n#define RB_FRAME_SAMPLER(slot, declaration) uniform declaration;\n#define RB_MATERIAL_BEGIN\n#define RB_MATERIAL_END\n#define RB_MATERIAL_AT(declaration, byte_offset) uniform declaration;\n#define RB_MATERIAL_SAMPLER(slot, declaration) uniform declaration;\n")
set(prelude_450 "#define RB_PER_FRAME_BEGIN layout(std140, set = 0, binding = 0) uniform RbPerFrame {\n#define RB_PER_FRAME_END };\n#define RB_PER_DRAW_BEGIN layout(push_constant) uniform RbPerDraw {\n#define RB_PER_DRAW_END };\n#define RB_PER_DRAW(declaration) declaration;\n#define RB_PER_DRAW_AT(declaration, byte_offset) layout(offset = byte_offset) declaration;\n#define RB_LIGHT_FRAME_BEGIN layout(std140, set = 0, binding = 1) uniform RbLights {\n#define RB_LIGHT_FRAME_END };\n#define RB_LIGHT_FRAME_AT(declaration, byte_offset) layout(offset = byte_offset) declaration;\n#define RB_FRAME_SAMPLER(slot, declaration) layout(set = 0, binding = slot) uniform declaration;\n#define RB_MATERIAL_BEGIN layout(std140, set = 1, binding = 0) uniform RbMaterial {\n#define RB_MATERIAL_END };\n#define RB_MATERIAL_AT(declaration, byte_offset) layout(offset = byte_offset) declaration;\n#define RB_MATERIAL_SAMPLER(slot, declaration) layout(set = 1, binding = slot) uniform declaration;\n")
if(DIALECT STREQUAL "410")
    set(version_line "#version 410 core\n")
    set(prelude "${prelude_410}")
else()
    set(version_line "#version 450\n")
    set(prelude "${prelude_450}")
endif()

set(prelude_constants "")
if(DEFINED PRELUDE)
    string(REPLACE "," ";" prelude_constants "${PRELUDE}")
endif()

set(directive "#include \"")
string(LENGTH "${directive}" directive_length)

string(REPLACE "," ";" entries "${MANIFEST}")
list(LENGTH entries entry_count)
if(DIALECT STREQUAL "450" AND NOT entry_count EQUAL 1)
    message(FATAL_ERROR "a 450 composition writes one GLSL file, so MANIFEST takes exactly one entry")
endif()

set(read_files "")
set(manifest_constants "")
if(DIALECT STREQUAL "410")
    set(header "#pragma once\n\n")
    string(APPEND header "// Generated by cmake/RabbetShaderCompose.cmake from the shader files.\n")
    string(APPEND header "// Edit those files, never this header.\n\n")
    string(APPEND header "namespace ${NAMESPACE} {\n")
endif()

foreach(entry IN LISTS entries)
    string(REGEX MATCH "^([A-Za-z0-9_]+)=(.+)$" matched "${entry}")
    if(NOT matched)
        message(FATAL_ERROR "malformed manifest entry '${entry}'")
    endif()
    set(constant "${CMAKE_MATCH_1}")
    list(APPEND manifest_constants "${constant}")
    set(body_file "${SHADER_DIR}/${CMAKE_MATCH_2}")
    if(NOT EXISTS "${body_file}")
        message(FATAL_ERROR "manifest entry '${entry}' names a missing file ${body_file}")
    endif()
    file(READ "${body_file}" remaining)
    list(APPEND read_files "${body_file}")

    set(expanded "")
    while(TRUE)
        string(FIND "${remaining}" "${directive}" position)
        if(position EQUAL -1)
            string(APPEND expanded "${remaining}")
            break()
        endif()
        if(position GREATER 0)
            math(EXPR before "${position} - 1")
            string(SUBSTRING "${remaining}" ${before} 1 previous_char)
            if(NOT previous_char STREQUAL "\n")
                message(FATAL_ERROR "${body_file} has an include that does not start a line")
            endif()
        endif()
        string(SUBSTRING "${remaining}" 0 ${position} prefix)
        string(APPEND expanded "${prefix}")
        math(EXPR name_start "${position} + ${directive_length}")
        string(SUBSTRING "${remaining}" ${name_start} -1 tail)
        string(FIND "${tail}" "\"" name_end)
        if(name_end EQUAL -1)
            message(FATAL_ERROR "${body_file} has an unterminated include name")
        endif()
        string(SUBSTRING "${tail}" 0 ${name_end} chunk_name)
        math(EXPR line_end "${name_end} + 1")
        string(SUBSTRING "${tail}" ${line_end} 1 line_terminator)
        if(NOT line_terminator STREQUAL "\n")
            message(FATAL_ERROR "${body_file} include line for '${chunk_name}' must end the line")
        endif()
        if(NOT EXISTS "${SHADER_DIR}/${chunk_name}")
            message(FATAL_ERROR "${body_file} includes missing chunk '${chunk_name}'")
        endif()
        file(READ "${SHADER_DIR}/${chunk_name}" chunk)
        list(APPEND read_files "${SHADER_DIR}/${chunk_name}")
        string(APPEND expanded "\n${chunk}")
        math(EXPR next_start "${line_end} + 1")
        string(SUBSTRING "${tail}" ${next_start} -1 remaining)
    endwhile()

    string(FIND "${expanded}" "#version" version_position)
    if(NOT version_position EQUAL -1)
        message(FATAL_ERROR "${body_file} or a chunk it includes must stay version free, the composer owns the version line")
    endif()
    # A directive surviving expansion means a chunk carried its own include, which the
    # single level scan above never resolves.
    string(FIND "${expanded}" "${directive}" leftover_position)
    if(NOT leftover_position EQUAL -1)
        message(FATAL_ERROR "${body_file} expanded to text that still contains an include directive")
    endif()

    set(composed_prefix "${version_line}")
    list(FIND prelude_constants "${constant}" prelude_position)
    if(NOT prelude_position EQUAL -1)
        string(APPEND composed_prefix "${prelude}")
    endif()

    if(DIALECT STREQUAL "450")
        file(WRITE "${OUTPUT}" "${composed_prefix}${expanded}")
    else()
        string(APPEND header "\ninline constexpr const char* ${constant} = R\"RBGLSL(${composed_prefix}")
        string(APPEND header "${expanded})RBGLSL\";\n")
    endif()
endforeach()

if(DIALECT STREQUAL "410")
    string(APPEND header "\n} // namespace ${NAMESPACE}\n")
    file(WRITE "${OUTPUT}" "${header}")
endif()

# A misspelled opt in would otherwise surface later as a GLSL failure on an
# unexpanded RB_ macro instead of naming the bad entry here.
foreach(prelude_constant IN LISTS prelude_constants)
    list(FIND manifest_constants "${prelude_constant}" prelude_found)
    if(prelude_found EQUAL -1)
        message(FATAL_ERROR "PRELUDE names '${prelude_constant}' which is not a manifest constant")
    endif()
endforeach()

if(DEFINED DEPFILE)
    list(REMOVE_DUPLICATES read_files)
    # Make prerequisite syntax splits on unescaped spaces, so a spaced checkout path
    # must arrive backslash escaped or it turns into bogus prerequisites.
    set(escaped_files "")
    foreach(read_file IN LISTS read_files)
        string(REPLACE " " "\\ " read_file "${read_file}")
        list(APPEND escaped_files "${read_file}")
    endforeach()
    string(REPLACE " " "\\ " escaped_output "${OUTPUT}")
    string(JOIN " " dependency_line ${escaped_files})
    file(WRITE "${DEPFILE}" "${escaped_output}: ${dependency_line}\n")
endif()
